language: go

go:
  - 1.2

install:
  - sudo apt-get install -y rubygems
  - gem install ronn
  - git clone https://github.com/anchor/libmarquise
  - cd libmarquise
  - autoreconf -i
  - ./configure && make && make check 
  - sudo make install
  - sudo /sbin/ldconfig
  - cd ../..

env:
  - PATH=/usr/sbin:/sbin:$GOPATH/bin:$PATH

script:
  # this should really be in the install step
  - sudo go install -a -race std
  - make all
